In [ ]:
pip install numpy


In [ ]:
import numpy as np

In [ ]:
arr0d=np.array(50)
arr1d=np.array([1,2,3])
print(arr1d)

[1 2 3]


In [ ]:
arr2d=np.array([[1,2,3],[4,5,6]])
print(arr2d)
print(arr2d[0,2])
print(arr2d[1,0])
print(arr2d[1,-2])

[[1 2 3]
 [4 5 6]]
3
4
5


In [ ]:
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[0,1,2],[3,4,5],[6,7,8]]])
print(arr3d)
print(arr3d.shape)
print(arr3d.size)
print(arr3d.dtype)
print(arr3d.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]]
(2, 3, 3)
18
int64
3


In [ ]:
print(arr0d.ndim)
print(arr1d.ndim)
print(arr2d.ndim)
print(arr3d.ndim)

0
1
2
3


In [ ]:
zeros=np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones=np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
random_arr=np.random.random((2,2))
print(random_arr)

[[0.89073026 0.54730438]
 [0.79399887 0.5367    ]]


In [ ]:
identity=np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
range_arr=np.arange(0,21,2)
print(range_arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1.shape)
print(arr1.size)#length
print(arr1.dtype)#data type
print(arr1.ndim)#No of dimensions

(2, 3)
6
int64
2


In [ ]:
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data.shape)
print(temp_data.size)
print(temp_data.dtype)
print(temp_data.ndim)

(2, 3)
6
int64
2


In [ ]:
updated_tempdata=np.array([[22,25,20],[24,26,23],[21,23,22]])
print(updated_tempdata)

[[22 25 20]
 [24 26 23]
 [21 23 22]]


In [ ]:
sensor_errorflags=np.zeros((2,3))
print(sensor_errorflags)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
greenhouse_identity=np.eye(3,3)
print(greenhouse_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(updated_tempdata)
print(sensor_errorflags)
print(greenhouse_identity)

[[22 25 20]
 [24 26 23]
 [21 23 22]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr2=np.array([[10,20],[40,50]])
print(arr2[:,1:])

[[20]
 [50]]


In [ ]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print(shipments[0,2])
print(shipments[1,6])

55
75


In [ ]:
print(shipments[:,0:5:1])

[[50 60 55 70 65]
 [40 45 50 60 55]]


In [ ]:
print(shipments[:,5:7])
print(shipments[0,2:6])

[[80 90]
 [70 75]]
[55 70 65 80]


In [ ]:
print(shipments)
shipments[0,5]=100
print(shipments)

[[50 60 55 70 65 80 90]
 [40 45 50 60 55 70 75]]
[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)#ele by ele addition
print(a*b)#ele by ele multiplication
print(a*2)
print(a)
a=a*b
print(a)

[5 7 9]
[ 4 10 18]
[2 4 6]
[1 2 3]
[ 4 10 18]


In [ ]:
mat1=np.array([[2,3],[4,5]])
print(np.sum(mat1))
print(np.prod(mat1))
mat2=np.array([[6,7],[8,9]])
print(mat1*mat2)#Element by element multiplication
res=np.dot(mat1,mat2)#Matrix multiplication
print(res)


14
120
[[12 21]
 [32 45]]
[[36 41]
 [64 73]]


In [ ]:
a1=np.array([1,2,3])
b1=2
print(a1+b1)#[3,4,5]

[3 4 5]


In [ ]:
x=5
y=10
z=np.add(x,y)
print(z)
print(np.subtract(x,y))
print(np.power(x,y))
print(np.divide(x,y))
np.log(x)
np.log10(y)
np.radians(y)
np.ceil(10.5)
np.trunc(10.9)
np.equal(x,y)
np.greater(x,y)

15
-5
9765625
0.5


np.False_

In [ ]:
farmA=np.zeros((4,3))
farmA[0]=[10,12,11]
farmA[1]=[9,11,10]
farmA[2]=[12,13,14]
farmA[3]=[8,7,9]
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
# farmC=np.ones((4,3))
rows=[]
rows.append([15,16,14])
rows.append([14,13,15])
rows.append([16,17,18])
rows.append([12,11,13])
farmC=np.array(rows)
print(farmA)
print(farmB)
print(farmC)

[[10. 12. 11.]
 [ 9. 11. 10.]
 [12. 13. 14.]
 [ 8.  7.  9.]]
[[20 19 21]
 [18 20 19]
 [22 23 21]
 [17 18 16]]
[[15 16 14]
 [14 13 15]
 [16 17 18]
 [12 11 13]]


In [ ]:
production_All=np.stack([farmA,farmB,farmC])
print(production_All)
print(production_All.shape)
print(production_All.size)
print(production_All.dtype)
print(production_All.ndim)


[[[10. 12. 11.]
  [ 9. 11. 10.]
  [12. 13. 14.]
  [ 8.  7.  9.]]

 [[20. 19. 21.]
  [18. 20. 19.]
  [22. 23. 21.]
  [17. 18. 16.]]

 [[15. 16. 14.]
  [14. 13. 15.]
  [16. 17. 18.]
  [12. 11. 13.]]]
(3, 4, 3)
36
float64
3


In [ ]:
# total_per_farm=np.array((3,))
# total_per_farm[0]=np.sum(production_All[0])
# # print(total_per_farm)
# total_per_farm[1]=np.sum(production_All[1])
# # print(total_per_farm)
# total_per_farm[2]=np.sum(production_All[2])
# print(total_per_farm)
total_per_farm=production_All.sum(axis=(1,2))
print(total_per_farm)
mean_per_farm=production_All.mean(axis=(1,2))
print(mean_per_farm)
std_per_farm=production_All.std(axis=(1,2))
print(std_per_farm)
var_per_farm=production_All.var(axis=(1,2))
print(var_per_farm)

[126. 234. 174.]
[10.5 19.5 14.5]
[1.97905701 1.97905701 1.97905701]
[3.91666667 3.91666667 3.91666667]


In [ ]:
hours_weights=np.array([0.5,1.0,0.75])
weighted_per_panel=np.dot(production_All,hours_weights)
print(weighted_per_panel)

[[25.25 23.   29.5  17.75]
 [47.   45.5  52.   40.75]
 [34.   31.25 38.5  26.75]]


In [ ]:
w2=0.5
production_All[1]+=w2
print(production_All)

[[[10.  12.  11. ]
  [ 9.  11.  10. ]
  [12.  13.  14. ]
  [ 8.   7.   9. ]]

 [[21.5 20.5 22.5]
  [19.5 21.5 20.5]
  [23.5 24.5 22.5]
  [18.5 19.5 17.5]]

 [[15.  16.  14. ]
  [14.  13.  15. ]
  [16.  17.  18. ]
  [12.  11.  13. ]]]


In [ ]:
mean_broadcast=mean_per_farm[:,np.newaxis,np.newaxis]
std_per_farm[:,np.newaxis,np.newaxis]
normalized=(production_All-mean_broadcast)/std_per_farm
print(normalized)

[[[-0.25264558  0.75793673  0.25264558]
  [-0.75793673  0.25264558 -0.25264558]
  [ 0.75793673  1.26322788  1.76851903]
  [-1.26322788 -1.76851903 -0.75793673]]

 [[ 1.01058231  0.50529115  1.51587346]
  [ 0.          1.01058231  0.50529115]
  [ 2.02116461  2.52645576  1.51587346]
  [-0.50529115  0.         -1.01058231]]

 [[ 0.25264558  0.75793673 -0.25264558]
  [-0.25264558 -0.75793673  0.25264558]
  [ 0.75793673  1.26322788  1.76851903]
  [-1.26322788 -1.76851903 -0.75793673]]]


In [ ]:
arr3=np.array([1,2,3,4,5,6])
print(arr3)
re_arr3=arr3.reshape(2,3)
print(re_arr3)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
c=np.array([1,2])
d=np.array([3,4])
e=np.array([6,7])
print(np.vstack((c,d,e)))#vertical stack
print(np.hstack((c,d,e)))#horizontal stack

[[1 2]
 [3 4]
 [6 7]]
[1 2 3 4 6 7]


In [ ]:
arr3=np.array([1,2,3,4,5])
print(np.array_split(arr3,4))

[array([1, 2]), array([3]), array([4]), array([5])]


In [ ]:
print(arr3)
print(arr3[arr3>3])
print(arr3)

[1 2 3 4 5]
[4 5]
[1 2 3 4 5]


In [ ]:
arr4=np.array([10,20,30,40,50])
indices=[0,2,4]
print(arr4[indices])

[10 30 50]


In [ ]:
#view shares the memory
#copy does not share memory
view=arr4.view()
view[3]=35
print(arr4)

[10 20 30 35 50]


In [ ]:
copy=arr4.copy()
copy[3]=40
print(arr4)

[10 20 30 35 50]


In [ ]:
#save and load
#np.save('filename',arr)   load_arr=np.load('filename')

In [ ]:
arr5=np.arange(10,51)
print(arr5)
print(arr5.shape)
print(arr5.size)
print(arr5.dtype)
print(arr5.ndim)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
(41,)
41
int64
1


In [ ]:
arr6=np.zeros((3,3))
arr6=np.random.rand(3,3)
print(arr6)
print(arr6.shape)
print(arr6.size)
print(arr6.dtype)
print(arr6.ndim)

[[0.89678384 0.78417411 0.07858617]
 [0.03005385 0.02490795 0.7171048 ]
 [0.19953148 0.1723958  0.93340191]]
(3, 3)
9
float64
2


In [ ]:
#w1=5
#arr5+=w1#
arr5=np.arange(10,51)
print(arr5+5)
n=np.array([[2,3],[4,5]])
m=np.array([[1,2],[2,3]])
print(n*m)
print(np.dot(n,m))

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[ 2  6]
 [ 8 15]]
[[ 8 13]
 [14 23]]


In [ ]:
arr7=np.arange(1,26).reshape(5,5)
print(arr7)
print(arr7[0])
print(arr7[:,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[ 5 10 15 20 25]


In [ ]:
print(arr7[0:3,0:2])

[[ 1  2]
 [ 6  7]
 [11 12]]


In [ ]:
arr8=np.random.randint(10,100,size=10)
print(arr8)

[17 70 48 63 93 84 73 17 71 53]


In [ ]:
np.min(arr8)
np.max(arr8)
np.mean(arr8)
np.std(arr8)


np.float64(24.37806390999909)

In [ ]:
arr9=np.arange(1,13).reshape(3,4)
print(arr9)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr10=np.ones((3,3))
print(arr10)
arr11=np.array([1,2,3])
print(arr10+arr11)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [ ]:
arr12=np.random.randint(1,50,size=30)
arr13=arr12[arr12% 5==0]
print(arr13)

[ 5 30 35]


In [ ]:
#arr14=np.ones((4,4))
arr14=np.array([[3,5,7,3],[2,8,4,1],[9,4,8,2],[2,6,3,1]])
print(arr14)
idx=np.arange(4)
arr15=arr14[idx,idx]
print(arr15)

[[3 5 7 3]
 [2 8 4 1]
 [9 4 8 2]
 [2 6 3 1]]
[3 8 8 1]
